### ISSUE TITLE
綴ミスの場所がありました

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#10]
https://github.com/Jun-Honda-0326/todo-app/blob/master/app/views/category/add.scala.html#L4

messagesPrivider: MessagesProvider

https://github.com/Jun-Honda-0326/todo-app/blob/master/conf/routes#L6

registar

https://vim-jp.org/vimdoc-ja/spell.html
これが良いのかわからないですが（Vimmerではないので。。）こういう綴チェック使うといいかもですな。

**Comment by Jun-Honda-0326** [comment]
訂正しました
