### ISSUE TITLE
htmlファイルの中で定義されているSeq

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#11]
口頭で話しましたが、
　 Seq("1" -> "赤", "2" -> "黄", "3" -> "青")
をhtmlファイルに記載されている場合があります。

https://github.com/Jun-Honda-0326/todo-app/blob/master/app/views/todo/edit.scala.html#L34
とかもですね。
Viewのhtmlファイル側では、定義を書くのをやめましょう。

**Comment by Jun-Honda-0326** [comment]
viewで使用するselectのOptionは各modelで定義しました。
viewではmodelで定義した値を呼び出して使用するような実装としています
