### ISSUE TITLE
Viewの中の表示ロジック

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#12]
https://github.com/Jun-Honda-0326/todo-app/blob/master/app/views/todo/list.scala.html#L27

27-30行までのロジックをController, ViewValueの中で書いて、
Viewの中ではその値で表示するようにしていきましょう。

**Comment by Jun-Honda-0326** [comment]
Controlelrでカテゴリーの情報を含んだvvを作成しこれをviewへ引数として渡すことで、viewでの処理を簡略化しました
