### ISSUE TITLE
ControllerからViewへのデータの渡し方で

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#13]
https://github.com/Jun-Honda-0326/todo-app/blob/master/app/controllers/todo/TodoController.scala#L101

Ok(views.html.todo.add(vv, categories))

の用に、vv, categoriesの２つのパラメータを渡すのではなく、vvに集約させていきましょう。

**Comment by Jun-Honda-0326** [comment]
todoの情報はvvに集約させて、タプル型にしてviewへ渡す実装へ修正しました
