### ISSUE TITLE
Viewでの日付表示に関して

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#14]
https://github.com/Jun-Honda-0326/todo-app/blob/master/app/views/category/list.scala.html#L27

以下の部分ですが、

  <td>@category.createdAt.format(DateTimeFormatter.ofPattern("yyy-MM-dd"))</td>

この書き方を他のところでも使っている場合を想定すると、ViewValueのメソッドとして纏めると良さそう。

**Comment by Jun-Honda-0326** [comment]
ViewmodelのViewValueCommonに日時表記をformatするメソッドを定義し、viewでそれを使用する形に実装しました
