### ISSUE TITLE
Todo Repository : 各種メソッド名に関して。

### ISSUE THREAD

**Issue by Masaya-Abe** [Jun-Honda-0326/todo-app#3]
メソッド名は基本動詞にしましょう。
scala のコレクションの メソッド名を参考にしてください。

todoAllByCategory -> filterByCategory
todoAllByState -> filterByState 

とか

---

insertNullByCategory このメソッド名も意味不明ですね。
まず insert でないので。 やってることは categoryId に紐づく state を 0 にしているだけなので、
`updateStatusToNull` とかの方がわかりやすいです。

**Comment by Jun-Honda-0326** [comment]
アドバイスと参考に見直しを行いました
