### ISSUE TITLE
CategoryController の I18nSupport の extend に関して

### ISSUE THREAD

**Issue by Masaya-Abe** [Jun-Honda-0326/todo-app#4]
これ必要でしょうか？いらないものであれば、不要なコードは書かないようにしましょう。

**Comment by Jun-Honda-0326** [comment]
これに関してはフォームの実装でinputが暗黙的にMessagesProviderの引数を必要としているので、この記述は必要と感じています。
現状の実装だとコンパイルエラーになってしまうので...

https://www.playframework.com/documentation/2.8.x/ScalaForms#Passing-MessagesProvider-to-Form-Helpers
