### ISSUE TITLE
EmbeddedId でなく、モデルを ViewValue に渡している部分。

### ISSUE THREAD

**Issue by Masaya-Abe** [Jun-Honda-0326/todo-app#5]
https://github.com/Jun-Honda-0326/todo-app/blob/master/app/controllers/category/CategoryController.scala#L54

この部分ですが、 map(_.v) する必要ありますか？
view 側で扱いずらくならないですかね。

**Comment by Jun-Honda-0326** [comment]
map(_.v)で処理しないとEmbeddedId型のままviewへ渡すことになってしまうためです。
idに関してはOptionに包まれてしまいますが、それ以外の値に関してはそのまま使用できるので、現状この方法での実装しか思い当たりませんでした

**Comment by TomokazuUehara** [comment]
@Jun-Honda-0326 さん

こちらは口頭で話しましたが、修正しましょう。
