### ISSUE TITLE
ViewValueCommonの見直し

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#7]
https://github.com/Jun-Honda-0326/todo-app/blob/master/app/model/Common.scala#L3

まず、ViewValueの使い方で、もともとのtodoのコードにあったViewValueCommonの中身をなぜか消してしまっていますね…
再度、他のディレクトリででも、todoのリポジトリをクローンして、ViewValueCommonをみてみましょう。
↓
次に、コレが何をしているのか？を理解し、
今、ViewValueCommonが継承している各ViewValue系のクラスを見直しましょう。

ViewValueのクラスではViewで表示したいデータを加工、表示で必要なメソッドなどを用意し、
Viewではロジックほぼ書かなくて、メソッドとかデータ呼び出すだけにしていきましょう。

**Comment by Jun-Honda-0326** [comment]
ViewValueCommonでcss、jsファイルを読込みこれを継承するようにしてTodo、CategoryのViewValueを定義する形に修正しました
