### ISSUE TITLE
importで不要なものを消しましょう

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#8]
細かい点ですが、importに不要なものが多い感じをうけました。
不要なものをみつけたら削除しましょう。

**Comment by Jun-Honda-0326** [comment]
一つにまとめるimportはなるべくまとめ　{TodoRepositry, CategoryRepository}
不要だと思ったimpotは削除しました。

**Comment by TomokazuUehara** [comment]
@Jun-Honda-0326 さん

CategoryContorollerの
 `import controllers.todo`

lib.mode.Todoファイルの
`import lib.model._`

など。Vimのプラグインで、使ってないインポートをお知らせしてくれるものがあるとよいのですが。
