### ISSUE TITLE
ViewValueのcase classについて

### ISSUE THREAD

**Issue by TomokazuUehara** [Jun-Honda-0326/todo-app#9]
ViewValueは各Viewと1対1をベースに仕上げていってください。
なんとなく、すくない？

↓

雑なIssueでしたね。先程会話しましたが、

ViewValueは、各Viewとベース1対1で考えつつ、
共通化できる所をまとめる

また、Controllerでvv以外に、他パラメータ渡しているものをvvの値に追加していきましょう。

**Comment by Jun-Honda-0326** [comment]
TodoのCategoryをvvに集約しました
